---
sidebar: sidebar 
permalink: install-setup/install-setup-requirements.html 
keywords: asa r2, install, setup, requirements, cautions 
summary: Reveja o equipamento necessário e as precauções de elevação para o seu sistema de armazenamento ASA r2 e prateleiras de armazenamento. 
---
= Requisitos de instalação para sistemas de storage ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Reveja o equipamento necessário e as precauções de elevação para o seu sistema de armazenamento ASA r2 e prateleiras de armazenamento.



== Equipamento necessário para instalação

Para instalar o sistema de storage ASA r2, você precisa dos seguintes equipamentos e ferramentas.

* Acesso a um navegador da Web para configurar o sistema de armazenamento
* Fita de descarga eletrostática (ESD)
* Lanterna
* Computador portátil ou console com conexão USB/serial
* Clipe de papel ou caneta esferográfica de ponta estreita para definir IDs de prateleira de armazenamento
* Chave de fendas Phillips nº 2




== Precauções de elevação

Os sistemas de storage e as gavetas de storage do ASA R2 são pesados. Tenha cuidado ao levantar e mover estes itens.



=== Pesos do sistema de armazenamento

Tome as precauções necessárias ao mover ou elevar o seu sistema de armazenamento ASA R2.

[role="tabbed-block"]
====
.A1K
--
Um sistema de armazenamento ASA A1K pode pesar até 28,5 kg (62,83 lbs). Para levantar o sistema de armazenamento, utilize duas pessoas ou um elevador hidráulico.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[Ícone de aviso de elevação do ASA A1K]

--
.A70 e A90
--
Um sistema de armazenamento ASA A70 ou ASA A90 pode pesar até 151,68 lbs (68,8 kg). Para levantar o sistema de armazenamento, utilize quatro pessoas ou um elevador hidráulico.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[Ícone de cuidado de peso ASA A90 ASA A70]

--
.A20, A30 E A50
--
Um sistema de armazenamento ASA A20, ASA A30 ou ASA A50 pode pesar até 27,9 kg (61,5 lbs). Para levantar o sistema de armazenamento, utilize duas pessoas ou um elevador hidráulico.

image::../media/drw_g_lifting_weight_ieops-1831.svg[Ícone de cuidado de peso ASA A20 A30 A50]

--
.C30
--
Um sistema de armazenamento ASA C30 pode pesar até 27,9 kg (61,5 lbs). Para levantar o sistema de armazenamento, utilize duas pessoas ou um elevador hidráulico.

image::../media/drw_g_lifting_weight_ieops-1831.svg[Ícone de cuidado de peso ASA A20 A30 ou A50]

--
====


=== Pesos da prateleira de armazenamento

Tome as precauções necessárias ao mover ou levantar a prateleira.

[role="tabbed-block"]
====
.NS224 gaveta
--
Uma prateleira de NS224 kg pode pesar até 66,78 lbs (30,29 kg). Para levantar a prateleira, use duas pessoas ou um elevador hidráulico. Mantenha todos os componentes na prateleira (dianteira e traseira) para evitar desequilibrar o peso da prateleira.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 NSM100 precaução de elevação]

--
.NS224 gaveta com NSM100B módulos
--
Uma prateleira NS224 com NSM100B módulos pode pesar até 56,8 lbs (25,8 kg). Para levantar a prateleira, use duas pessoas ou um elevador hidráulico. Mantenha todos os componentes na prateleira (dianteira e traseira) para evitar desequilibrar o peso da prateleira.

image::../media/drw_ns224_nsm100b_lifting_weight_ieops-1832.svg[NS224 com NSM100b cuidado de elevação]

--
====
.Informações relacionadas
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informações de segurança e avisos regulamentares"^]


.O que se segue?
Depois de analisar os requisitos de hardware, você link:prepare-hardware.html["Prepare-se para instalar o sistema de storage ASA r2"].
