---
sidebar: sidebar 
permalink: install-setup/prepare-hardware.html 
keywords: prepare, hardware installation, aff a1k, aff a70, aff a90, aff c80, asa r2, asa a1k, asa a90, asa a70, asa a30, asa a20, asa a50, asa c30 
summary: Prepare-se para instalar o sistema de storage ASA R2 em seu ambiente ONTAP e Registre o hardware para ter acesso aos benefícios de suporte. 
---
= Prepare-se para instalar um sistema de storage ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prepare-se para instalar seu sistema de armazenamento ASA r2, preparando o site, desembalando as caixas e comparando o conteúdo das caixas com o slip de embalagem e registrando o sistema para acessar os benefícios de suporte.



== Passo 1: Prepare o site

Para instalar o sistema de armazenamento ASA R2, certifique-se de que o local e o gabinete ou rack que você planeja usar atendam às especificações de sua configuração.

.Passos
. Use https://hwu.netapp.com["NetApp Hardware Universe"^] para confirmar se o local atende aos requisitos ambientais e elétricos do sistema de armazenamento.
. Certifique-se de ter espaço adequado para o gabinete ou rack para o seu sistema de armazenamento, prateleiras e todos os switches:
+
[role="tabbed-block"]
====
.A1K
--
** 4U em uma configuração de HA
** 2U TB para cada compartimento de armazenamento de NS224 TB
** 1U para a maioria dos interrutores


--
.A70 e A90
--
** 4U em uma configuração de HA
** 2U TB para cada compartimento de armazenamento de NS224 TB
** 1U para a maioria dos interrutores


--
.A20, A30 E A50
--
** 2U para um sistema de storage
** 2U TB para cada compartimento de armazenamento de NS224 TB
** 1U para a maioria dos interrutores


--
.C30
--
** 2U para um sistema de storage
** 2U TB para cada compartimento de armazenamento de NS224 TB
** 1U para a maioria dos interrutores


--
====


. Instale todos os switches de rede necessários.
+
Consulte o https://docs.netapp.com/us-en/ontap-systems-switches/index.html["Documentação do switch"^] para obter instruções de instalação e link:https://hwu.netapp.com["NetApp Hardware Universe"^] para obter informações sobre compatibilidade.





== Passo 2: Desembale as caixas

Depois de garantir que o local e o gabinete ou rack que você planeja usar para o seu sistema de armazenamento ASA R2 atendam às especificações necessárias, desembale todas as caixas e compare o conteúdo com os itens no folheto de embalagem.

.Passos
. Abra cuidadosamente todas as caixas e coloque o conteúdo de forma organizada.
. Compare o conteúdo que você descompactou com a lista no folheto de embalagem. Se houver discrepâncias, anote-as para outras ações.
+
Você pode obter sua lista de embalagem digitalizando o código QR no lado da caixa de transporte.

+
Os itens a seguir são alguns dos conteúdos que você pode ver nas caixas.

+
[cols="12,9,4"]
|===


| *Hardware* | *Cabos* |  


 a| 
** Painel frontal
** Sistema de storage
** Kits de trilhos com instruções (opcional)
** Prateleira de armazenamento (se você pediu armazenamento adicional)

 a| 
** Cabos Ethernet de gerenciamento (cabos RJ-45)
** Cabos de rede
** Cabos de energia
** Cabos de armazenamento (se você tiver pedido armazenamento adicional)
** Cabo de porta serial USB-C.

|  
|===




== Passo 3: Registre seu sistema de armazenamento

Depois de garantir que seu local atenda aos requisitos das especificações do sistema de storage ASA R2 e verificar se tem todas as peças que você solicitou, você deve Registrar seu sistema.

.Passos
. Localize os números de série do seu sistema de armazenamento.
+
Você pode encontrar os números de série nos seguintes locais:

+
** Sobre o deslizamento da embalagem
** No seu e-mail de confirmação
** Em cada controlador ou em alguns sistemas, no módulo de gestão do sistema de cada controlador
+
image::../media/drw_ssn_label.svg[Exemplo do número de série do sistema]



. Vá para http://mysupport.netapp.com/["Site de suporte da NetApp"^] .
. Determine se você precisa Registrar seu sistema de storage:
+
[cols="1a,2a"]
|===
| Se você é um... | Siga estes passos... 


 a| 
Cliente NetApp existente
 a| 
.. Inicie sessão com o seu nome de utilizador e palavra-passe.
.. Selecione *sistemas* > *Meus sistemas*.
.. Confirme se o novo número de série está listado.
.. Se o número de série não estiver listado, siga as instruções para novos clientes NetApp.




 a| 
Novo cliente da NetApp
 a| 
.. Clique em *Registe-se agora* e crie uma conta.
.. Selecione *Systems* > *Register Systems*.
.. Introduza o número de série do sistema de armazenamento e os detalhes solicitados.


Após a aprovação do seu registo, pode transferir qualquer software necessário. O processo de aprovação pode demorar até 24 horas.

|===


.O que se segue?
Depois de se preparar para instalar o hardware do ASA R2, link:deploy-hardware.html["Instale o hardware do seu sistema de storage ASA r2"]você .
