---
sidebar: sidebar 
permalink: install-setup/set-up-data-access.html 
keywords:  
summary:  
---
= Habilite o acesso a dados de hosts SAN ao seu sistema de storage ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para configurar o acesso aos dados, você deve garantir que os parâmetros críticos e as configurações do seu cliente SAN para operação adequada com o ONTAP estejam configurados corretamente. Se você estiver fornecendo armazenamento para o seu ambiente VMware, instale o OTV 10,3 para simplesmente o gerenciamento do armazenamento do ASA R2.



== Configurar o acesso a dados a partir de hosts SAN

A configuração necessária para configurar o acesso de dados ao seu sistema ASA R2 a partir de seus hosts SAN varia dependendo do sistema operacional do host e do protocolo. A configuração correta é importante para o melhor desempenho e o failover bem-sucedido.

Consulte a documentação do host SAN ONTAP para link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["Clientes SCSI do VMware vSphere"^] link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Clientes NVMe do VMware vSphere"^]e link:https://docs.netapp.com/us-en/ontap-sanhost/overview.html["Outros clientes SAN"^] para configurar corretamente os hosts para se conetar ao sistema ASA R2.



== Migrar máquinas virtuais VMware

Se você precisar migrar seu workload de VM de um sistema de storage ASA para um sistema de storage ASA R2, a NetApp recomenda que você link:https://www.vmware.com/products/cloud-infrastructure/vsphere/vmotion["VMware vSphere vMotion"^]execute uma migração ativa e sem interrupções dos dados.



== Configure o sistema ASA R2 como um fornecedor de storage no ambiente VMware

Você pode usar as ferramentas do ONTAP para VMware para habilitar facilmente o sistema ASA R2 como fornecedor de storage no ambiente VMware.

O ONTAP Tools for VMware vSphere é um conjunto de ferramentas que funcionam em conjunto com o VMware vCenter Server Virtual Appliance (vCSA) para facilitar o gerenciamento de máquinas virtuais em seus hosts VMware ESXi.

Os sistemas ASA R2 são suportados pela link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/concepts/ontap-tools-overview.html["Ferramentas do ONTAP para VMware vSphere 10,3"] e posteriores.

Saiba como link:https://review.docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10_otv103-releasebranch/deploy/ontap-tools-deployment.html["Implantar as ferramentas do ONTAP para VMware"^]e, em seguida, use-o para fazer o seguinte:

* link:https://review.docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10_otv103-releasebranch/configure/add-vcenter.html["Adicione instâncias do vCenter Server"^]
* link:https://review.docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10_otv103-releasebranch/configure/configure-esx-server-multipath-and-timeout-settings.html["Configure as configurações do host ESXi"^]
* link:https://review.docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10_otv103-releasebranch/configure/discover-storage-systems-and-hosts.html["Descubra os hosts e o sistema de storage do ASA R2"^]


.O que se segue?
Você está pronto link:../manage-data/provision-san-storage.html["provisionamento de storage"]para permitir que seus hosts SAN leiam e gravem dados em unidades de storage.
