---
sidebar: sidebar 
permalink: secure-data/migrate-encryption-keys-between-key-managers.html 
keywords: onboard key manager, external key manager, configure, migrate keys, store keys, authentication keys, encryption keys, asa r2 
summary: 'Você pode usar o Gerenciador de chaves integrado do ONTAP no sistema ASA R2, um gerenciador de chaves externo ou ambos (em um caso) para gerenciar chaves de criptografia de dados.' 
---
= Migrar as chaves de criptografia de dados ONTAP entre gerenciadores de chaves em sistemas ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode gerenciar as chaves de criptografia de dados com o ONTAP onboard key manager no seu sistema ASA r2, um gerenciador de chaves externo ou ambos, em configurações compatíveis. Gerenciadores de chaves externos são compatíveis apenas no nível da storage VM. No nível do cluster ONTAP, você pode usar o onboard key manager ou um gerenciador de chaves externo.

[cols="2,2"]
|===
| Se ativar o seu gestor de chaves na... | Você pode usar... 


| Somente no nível do cluster  a| 
O gerenciador de chaves integrado ou um gerenciador de chaves externo



| Somente no nível de VM de armazenamento | Apenas um gerenciador de chaves externo 


 a| 
Tanto no nível do cluster quanto no nível da VM de armazenamento
 a| 
Uma das seguintes combinações de gerenciador de chaves:

* Opção 1
+
Nível de cluster: Gerenciador de chaves integrado

+
Nível de VM de armazenamento: Gerenciador de chaves externo

* Opção 2
+
Nível de cluster: Gerenciador de chaves externo

+
Nível de VM de armazenamento: Gerenciador de chaves externo



|===


[[migrate-keys-between-key-managers-at-the-ontap-cluster-level]]
== Migre chaves entre os gerenciadores-chave no nível do cluster do ONTAP

A partir do ONTAP 9.16.1, você pode usar a interface de linha de comando do ONTAP (CLI) para migrar chaves entre gerenciadores de chaves no nível do cluster.

[role="tabbed-block"]
====
.Do gestor de chaves integrado ao gestor de chaves externo
--
.Passos
. Defina o nível de privilégio como avançado:
+
[source, cli]
----
set -privilege advanced
----
. Criar uma configuração de gerenciador de chaves externo inativo:
+
[source, cli]
----
security key-manager external create-config
----
. Mude para o gerenciador de chaves externo:
+
[source, cli]
----
security key-manager keystore enable -vserver <storage_vm_name> -type KMIP
----
. Exclua a configuração do gerenciador de chaves integrado:
+
[source, cli]
----
security key-manager keystore delete-config -vserver <storage_vm_name> -type OKM
----
. Defina o nível de privilégio como admin:
+
[source, cli]
----
set -privilege admin
----


--
.De key manager externo para key manager onboard
--
.Passos
. Defina o nível de privilégio como avançado:
+
[source, cli]
----
set -privilege advanced
----
. Criar uma configuração inativa do gerenciador de chaves integrado:
+
[source, cli]
----
security key-manager onboard create-config
----
. Ative a configuração do gerenciador de chaves integrado:
+
[source, cli]
----
security key-manager keystore enable -vserver <storage_vm_name> -type OKM
----
. Exclua a configuração do gerenciador de chaves externas
+
[source, cli]
----
security key-manager keystore delete-config -vserver <storage_vm_name> -type KMIP
----
. Defina o nível de privilégio como admin:
+
[source, cli]
----
set -privilege admin
----


--
====


[[migrate-keys-between-key-managers-across-ontap-cluster-and-storage-vm-levels]]
== Migre chaves entre gerenciadores de chaves em cluster ONTAP e níveis de VM de armazenamento

Você pode usar a interface de linha de comando do ONTAP (CLI) para migrar chaves entre gerenciadores de chaves nos níveis de cluster e de máquina virtual de armazenamento.

.Passos
. Defina o nível de privilégio como avançado:
+
[source, cli]
----
set -privilege advanced
----
. Migrar as chaves:
+
[source, cli]
----
security key-manager key migrate -from-vserver <storage_vm_name> -to-vserver <storage_vm_name>
----
. Defina o nível de privilégio como admin:
+
[source, cli]
----
set -privilege admin
----

