---
sidebar: sidebar 
permalink: secure-data/modify-arp-snapshot-retention-period.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, ai, alerts, respond, warnings, security 
summary: Aprenda como modificar os períodos de retenção de snapshots do ARP para atender às suas necessidades de armazenamento e negócios. 
---
= Modificar períodos de retenção de snapshots ARP/AI em sistemas de armazenamento ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se a Proteção Autônoma contra Ransomware com Inteligência Artificial (ARP/AI) detectar atividade anormal em uma ou mais unidades de armazenamento no seu ASA r2, ela criará automaticamente um snapshot ARP para proteger os dados. Dependendo da sua capacidade de storage e dos requisitos do seu negócio, você pode querer aumentar ou diminuir o período de retenção padrão do snapshot ARP. Por exemplo, você pode aumentar o período de retenção para aplicativos críticos para os negócios, para oferecer janelas de recuperação de dados mais longas, ou diminuí-lo para aplicativos não críticos para economizar espaço de storage.

O período de retenção padrão para o snapshot do ARP varia dependendo da ação que você toma em resposta à atividade anormal.

[cols="2,2"]
|===
| Se você tomar essa atitude... | Os instantâneos ARP são retidos por padrão para... 


| Marcar como falso positivo | 12 horas 


| Marcar como potencial ataque de ransomware | 7 dias 


| Não tome medidas imediatas | 10 dias 
|===
Você pode modificar os períodos de retenção padrão usando a interface de linha de comando do ONTAP (CLI). Consulte  https://docs.netapp.com/us-en/ontap/anti-ransomware/modify-automatic-snapshot-options-task.html["Modificar opções para snapshots automáticos do ONTAP"] para ver as etapas para alterar o período de retenção padrão.
