---
sidebar: sidebar 
permalink: secure-data/respond-anti-ransomware-protection-alerts.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, ai, alerts, respond, warnings, security 
summary: Veja avisos de possíveis ataques de ransomware e tome medidas no Gerenciador do Sistema. 
---
= Responder a alertas ARP/AI em sistemas de armazenamento ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se a Proteção Autônoma contra Ransomware com Inteligência Artificial (ARP/AI) detectar atividade anormal em uma ou mais unidades de storage no seu ASA r2, o System Manager exibirá um aviso no painel. Analise o aviso, verifique a atividade e tome as medidas necessárias para proteger seus dados.

Se uma mensagem de aviso ARP/AI for exibida, use o verificador de integridade de aplicativos apropriado para verificar os dados na unidade de armazenamento antes de tomar qualquer providência. Verificar a integridade de dados da unidade de armazenamento ajuda você a determinar se a atividade é aceitável ou se trata de um possível ataque de ransomware.

[cols="2,2"]
|===
| Se a atividade anormal for ... | Então faça isto... 


| Aceitável | Marque a atividade como um falso positivo. 


| Um potencial ataque de ransomware | Marque a atividade como um possível ataque de ransomware. 


| Indeterminado | Não tome nenhuma providência imediata. Monitore a unidade de armazenamento por até 7 dias. Se a unidade de armazenamento continuar a operar normalmente, marque a atividade como um falso positivo. Se a unidade de armazenamento continuar apresentando atividade anormal, marque a atividade como um possível ataque de ransomware. 
|===
.Passos
. No System Manager, selecione *Dashboard*.
+
Se o ARP/AI detectar atividade anormal em uma ou mais unidades de armazenamento, uma mensagem aparece em *Avisos*.

. Selecione a mensagem de aviso.
. Em *Visão geral de eventos*, selecione a mensagem *Avisos* que indica o número de unidades de armazenamento com atividade anormal.
. Em *Unidades de armazenamento com atividade anormal*, selecione a unidade de armazenamento.
. Selecione *Segurança*.
+
Se houver atividade anormal na unidade de armazenamento, uma mensagem será exibida em *Anti-ransomware*.

. Selecione *Escolher uma ação*.
. Selecione *Marcar como falso positivo* ou selecione *Marcar como possível ataque de ransomware*.


.O que se segue?
Se você observar picos na atividade de suas unidades de armazenamento, sejam eles pontuais ou característicos de um novo padrão, você deve reportá-los como seguros. Reportar esses picos manualmente como seguros ajuda a melhorar a precisão das avaliações de ameaças do ARP. Saiba como link:https://docs.netapp.com/us-en/ontap/anti-ransomware/manage-parameters-task.html#report-known-surges["relatar picos conhecidos de ARP/AI"^].
