---
sidebar: sidebar 
permalink: learn-more/hardware-comparison.html 
keywords: compare asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, hardware comparison, asa r2 
summary: Os sistemas ASA oferecem suporte a hardware otimizado para soluções somente SAN. Os sistemas ASA R2 oferecem otimização de hardware e software. 
searchtitle: Compare os sistemas ASA R2 com outros sistemas ONTAP 
---
= Compare os sistemas ASA R2 com outros sistemas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os sistemas ASA R2 oferecem uma solução de hardware e software para ambientes somente SAN desenvolvidos em plataformas all-flash. Os sistemas ASA R2 variam de outros sistemas ONTAP (ASA, AFF e FAS) na implementação de sua camada de storage, protocolos compatíveis e personalidade do ONTAP.

Em um sistema ASA R2, o software ONTAP é otimizado para oferecer suporte à funcionalidade essencial da SAN, ao mesmo tempo em que limita a visibilidade e a disponibilidade de recursos e funções que não sejam relacionados à SAN. Por exemplo, o Gerenciador de sistema em execução em um sistema ASA R2 não exibe opções para criar diretórios base para clientes nas. Esta versão simplificada do ONTAP é identificada como a personalidade _ASA R2_. O ONTAP executado em sistemas ASA é identificado como _ASA ONTAP Personality_. ONTAP executado em sistemas AFF e FAS ONTAP é identificado como a personalidade ONTAP unificada_. As diferenças entre as personalidades do ONTAP são referenciadas na referência de comando do ONTAP (páginas man), na especificação REST API e nas mensagens EMS, quando aplicável.

Você pode verificar a personalidade do seu storage da ONTAP no Gerenciador do sistema ou na CLI do ONTAP.

* No menu System Manager, selecione *Cluster > Overview*.
* Na CLI, digite: `san config show`


A personalidade do seu sistema de storage ONTAP não pode ser alterada.

A camada de storage para sistemas ONTAP que executam a personalidade ONTAP unificada usa agregados como unidade base de storage. Um agregado possui um conjunto específico de discos disponíveis em um sistema de storage. O agregado aloca espaço nos discos que possui para volumes para LUNs e namespaces. Um usuário unificado do ONTAP pode usar a interface de linha de comando (CLI) para criar e modificar agregados, volumes, LUNs e namespaces.

A camada de storage em sistemas ASA R2 usa uma zona de disponibilidade de storage em vez de agregados. Uma zona de disponibilidade de armazenamento é um pool comum de armazenamento que tem acesso a todos os discos disponíveis no sistema de armazenamento. A zona de disponibilidade de storage fica visível para ambos os nós em um par de HA ASA R2. Quando uma unidade de armazenamento (baseada em um LUN ou um namespace NVMe) é criada, o ONTAP cria automaticamente um volume dentro da máquina virtual de armazenamento (VM) selecionada na zona de disponibilidade de armazenamento para hospedar a unidade de armazenamento. Devido a essa abordagem automatizada e simplificada para o gerenciamento de storage, certas opções do System Manager, comandos ONTAP e pontos de extremidade da API REST não estão disponíveis ou têm uso limitado em um sistema ASA R2. Por exemplo, como a criação e o gerenciamento de volumes são automatizados para sistemas ASA R2, o menu *volumes* não aparece no Gerenciador de sistemas e o `volume create` comando não é suportado.

O storage do ASA R2 é comparado a outros sistemas de storage da ONTAP das seguintes maneiras:

[cols="1h,2,2,2,2"]
|===
|  | ASA r2 | ASA | AFF | FAS 


 a| 
*Personalidade ONTAP*
| ASA r2 | ASA | Unificado | Unificado 


 a| 
*Suporte ao protocolo SAN*
| Sim | Sim | Sim | Sim 


 a| 
*Suporte ao protocolo nas*
| Não | Não | Sim | Sim 


 a| 
*Suporte de camada de armazenamento*
| Zona de disponibilidade de armazenamento | Agregados | Agregados | Agregados 
|===
As seguintes plataformas ASA são classificadas como sistemas ASA R2:

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20
* ASA C30


.Para mais informações
* Saiba mais link:https://docs.netapp.com/us-en/ontap-systems-family/intro-family.html["Sistemas de hardware ONTAP"^]sobre o .
* Consulte o suporte completo à configuração e as limitações dos sistemas ASA e ASA R2 no link:https://hwu.netapp.com/["NetApp Hardware Universe"^].
* Saiba mais sobre o link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"^].




== Resumo das diferenças do sistema ASA R2

As principais diferenças entre os sistemas ASA R2 e os sistemas FAS, AFF e ASA relevantes para a interface de linha de comando (CLI) do ONTAP e API REST são descritas abaixo.

.Criação padrão de SVM com serviços de protocolo
Os novos clusters contêm automaticamente um SVM de dados padrão com os protocolos SAN ativados. Os LIFs de dados IP suportam protocolos iSCSI e NVMe/TCP e usam a `default-data-blocks` política de serviço por padrão.

.Criação automática de volume
A criação de uma unidade de armazenamento (LUN ou namespace) cria automaticamente um volume a partir da zona de disponibilidade de armazenamento. Isso resulta em um namespace simplificado e comum. Eliminar uma unidade de armazenamento elimina automaticamente o volume associado.

.Alterações no provisionamento fino e espesso
As unidades de storage são sempre provisionadas de forma fina nos sistemas de storage ASA R2. O provisionamento espesso não é suportado.

.Alterações na compressão de dados
A eficiência de storage sensível à temperatura não é aplicada em sistemas ASA R2. Em sistemas ASA R2, a compactação não é baseada em dados _hot_ (acessados com frequência) ou dados _cold_ (acessados com pouca frequência). A compactação começa sem esperar que os dados fiquem frios.
