---
sidebar: sidebar 
permalink: learn-more/hardware-comparison.html 
keywords: compare asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, hardware comparison, asa r2 
summary: Os sistemas ASA oferecem suporte a hardware otimizado para soluções somente SAN. Os sistemas ASA R2 oferecem otimização de hardware e software. 
searchtitle: Compare os sistemas ASA R2 com outros sistemas ONTAP 
---
= Compare os sistemas ASA R2 com outros sistemas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os sistemas ASA r2 oferecem uma solução de hardware e software para ambientes exclusivamente SAN, construída com base em soluções all-flash. Os sistemas ASA r2 diferem de outros sistemas ONTAP (ASA, AFF e FAS) na implementação de sua personalidade ONTAP , camada de armazenamento e protocolos suportados.

Os seguintes sistemas são classificados como sistemas ASA r2:

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20
* ASA C30




== Diferenças de personalidade

Em um sistema ASA R2, o software ONTAP é otimizado para oferecer suporte à funcionalidade essencial da SAN, ao mesmo tempo em que limita a visibilidade e a disponibilidade de recursos e funções que não sejam relacionados à SAN. Por exemplo, o Gerenciador de sistema em execução em um sistema ASA R2 não exibe opções para criar diretórios base para clientes nas. Esta versão simplificada do ONTAP é identificada como a personalidade _ASA R2_. O ONTAP executado em sistemas ASA é identificado como _ASA ONTAP Personality_. ONTAP executado em sistemas AFF e FAS ONTAP é identificado como a personalidade ONTAP unificada_. As diferenças entre as personalidades do ONTAP são referenciadas na referência de comando do ONTAP (páginas man), na especificação REST API e nas mensagens EMS, quando aplicável.

Você pode verificar a personalidade do seu storage da ONTAP no Gerenciador do sistema ou na CLI do ONTAP.

* No menu System Manager, selecione *Cluster > Overview*.
* Na CLI, digite: `system node show -personality -is-disaggregated`


Para sistemas ASA r2, a _personalidade_ é _ASA r2_ e o status de _é-desagregado_ é _verdadeiro_.

A personalidade do seu sistema de storage ONTAP não pode ser alterada.



== Diferenças na camada de armazenamento

Os sistemas ASA r2 usam uma camada de armazenamento simplificada que é diferente da camada de armazenamento usada pelos sistemas FAS, AFF e ASA .

.Sistemas FAS, AFF e ASA
A camada de armazenamento para sistemas FAS, AFF e ASA utiliza agregados como unidade base de armazenamento. Um agregado possui um conjunto específico de discos disponíveis em um sistema de armazenamento. O agregado aloca espaço nos discos que possui para volumes para LUNs e namespaces. Com esses sistemas, os usuários do ONTAP podem criar e modificar agregados, volumes, LUNs e namespaces.

.Sistemas ASA r2
Em vez de agregados, a camada de armazenamento em sistemas ASA r2 utiliza zonas de disponibilidade de armazenamento. Uma zona de disponibilidade de armazenamento é um conjunto comum de armazenamento disponível para ambos os nós de um único par de alta disponibilidade. Ambos os nós no par de alta disponibilidade têm acesso a todos os discos disponíveis em sua zona de disponibilidade de armazenamento compartilhada. Por exemplo, em um cluster ONTAP de um sistema ASA r2 de 2 nós, há uma zona de disponibilidade de armazenamento, acessível por ambos os nós do cluster. Em um cluster ONTAP de um sistema ASA r2 de 4 nós, há duas zonas de disponibilidade de armazenamento. Cada par de alta disponibilidade no cluster tem acesso a uma das zonas de disponibilidade de armazenamento.

Quando uma unidade de armazenamento (baseada em um LUN ou em um namespace NVMe) é criada, o ONTAP cria automaticamente um volume na zona de disponibilidade de armazenamento apropriada para abrigar a unidade de armazenamento. O volume recém-criado é automaticamente colocado na zona de disponibilidade de armazenamento para desempenho ideal e utilização equilibrada da capacidade. == Resumo das diferenças do sistema ASA r2

Os sistemas ASA r2 diferem dos sistemas FAS, AFF e ASA nas seguintes maneiras:

[cols="1h,2,2,2,2"]
|===
|  | ASA r2 | ASA | AFF | FAS 


 a| 
*Personalidade ONTAP*
| ASA r2 | ASA | Unificado | Unificado 


 a| 
*Suporte ao protocolo SAN*
| Sim | Sim | Sim | Sim 


 a| 
*Suporte ao protocolo nas*
| Não | Não | Sim | Sim 


 a| 
*Suporte de camada de armazenamento*
| Zona de disponibilidade de armazenamento | Agregados | Agregados | Agregados 
|===
Devido a essa abordagem automatizada e simplificada para o gerenciamento de armazenamento, certas opções do Gerenciador de Sistemas, comandos ONTAP e endpoints da API REST não estão disponíveis ou têm uso limitado em um sistema ASA r2. Por exemplo, como a criação e o gerenciamento de volumes são automatizados para sistemas ASA r2, o menu *Volumes* não aparece no Gerenciador de Sistemas e o  `volume create` O comando não é suportado. link:cli-support.html["Saiba mais sobre comandos ASA r2 não suportados"] .

As principais diferenças entre os sistemas ASA R2 e os sistemas FAS, AFF e ASA relevantes para a interface de linha de comando (CLI) do ONTAP e API REST são descritas abaixo.

.Criação de VM de armazenamento padrão com serviços de protocolo
Os novos clusters contêm automaticamente uma máquina virtual (VM) de armazenamento de dados padrão com os protocolos SAN ativados.  Os LIFs de dados IP suportam os protocolos iSCSI e NVMe/TCP e utilizam o `default-data-blocks` Política de serviço por padrão.

.Criação automática de volume
A criação de uma unidade de armazenamento (LUN ou namespace) cria automaticamente um volume a partir da zona de disponibilidade de armazenamento. Isso resulta em um namespace simplificado e comum. Eliminar uma unidade de armazenamento elimina automaticamente o volume associado.

.Alterações no provisionamento fino e espesso
As unidades de storage são sempre provisionadas de forma fina nos sistemas de storage ASA R2. O provisionamento espesso não é suportado.

.Alterações na compressão de dados
A eficiência de storage sensível à temperatura não é aplicada em sistemas ASA R2. Em sistemas ASA R2, a compactação não é baseada em dados _hot_ (acessados com frequência) ou dados _cold_ (acessados com pouca frequência). A compactação começa sem esperar que os dados fiquem frios.

.Para mais informações
* Saiba mais link:https://docs.netapp.com/us-en/ontap-systems-family/intro-family.html["Sistemas de hardware ONTAP"^]sobre o .
* Consulte o suporte completo à configuração e as limitações dos sistemas ASA e ASA R2 no link:https://hwu.netapp.com/["NetApp Hardware Universe"^].
* Saiba mais sobre o link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"^].

