---
sidebar: sidebar 
permalink: learn-more/software-support-limitations.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa, a50, asa a30, asa a20, asa c30, unsupported features 
summary: Embora os sistemas ASA R2 ofereçam uma ampla gama de suporte para soluções SAN, certos recursos de software ONTAP não são suportados. 
---
= Suporte e limitações do software ONTAP para sistemas de storage ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Embora os sistemas ASA R2 ofereçam uma ampla gama de suporte para soluções SAN, certos recursos de software ONTAP não são suportados.

.Os sistemas ASA R2 não suportam o seguinte:
* FabricPool
* Provisionamento de espessura de LUN
* MetroCluster
* Criptografia de agregado NetApp (NAE)
* Protocolos de objetos
* ONTAP S3 SnapMirror e S3 APIs
* SnapLock
+
SnapLock Compliance e Enterprise não são suportados em clusters primários em ambientes SAN. SnapLock for SnapVault é suportado em clusters secundários.

* A replicação SnapMirror é suportada em sistemas ASA r2 com as seguintes limitações:
+
** A replicação síncrona do SnapMirror não é suportada.
** A replicação assíncrona do SnapMirror é suportada apenas entre dois sistemas ASA r2. A replicação assíncrona do SnapMirror não é suportada entre um sistema ASA r2 e um sistema ASA, AFF ou FAS , ou a nuvem.
+
Saiba mais sobrelink:../data-protection/pre-defined-protection-policies.html["Políticas de replicação SnapMirror suportadas em sistemas ASA r2"] .

** O SnapMirror ActiveSync é compatível apenas entre dois sistemas ASA R2.
+
Saiba mais sobrelink:../data-protection/snapmirror-active-sync.html["Sincronização ativa do SnapMirror em sistemas ASA r2"] .





.Os sistemas ASA R2 suportam o seguinte:
* Criptografia de camada dupla
+
Os sistemas ASA r2 suportam criptografia de hardware usando unidades de auto-criptografia (SEDs) e criptografia de software usando a tecnologia NetApp Volume Encryption (NVE). link:../secure-data/encrypt-data-at-rest.html["Saiba como aplicar criptografia de camada dupla"] para proteger os dados no seu sistema ASA r2.



.Para mais informações
* Consulte o link:https://hwu.netapp.com/["NetApp Hardware Universe"^] para obter mais informações sobre o suporte e limitações de hardware do ASA R2.

