---
sidebar: sidebar 
permalink: learn-more/software-support-limitations.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa, a50, asa a30, asa a20, asa c30, unsupported features 
summary: Embora os sistemas ASA R2 ofereçam uma ampla gama de suporte para soluções SAN, certos recursos de software ONTAP não são suportados. 
---
= Suporte e limitações do software ONTAP para sistemas de storage ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Embora os sistemas ASA R2 ofereçam uma ampla gama de suporte para soluções SAN, certos recursos de software ONTAP não são suportados.

.Os sistemas ASA R2 não suportam o seguinte:
* Failover automático de iSCSI LIF predefinido
+
Nos sistemas ASA R2, o LIF de rede padrão é compartilhado entre hosts NVMe e SCSI, portanto, não é compatível com failover automático. Para ativar o failover automático de LIF iSCSI, é link:../administer/manage-client-vm-access.html#create-a-lif-network-interface["Crie um LIF apenas iSCSI"]necessário . O failover automático é ativado no iSCSI Only LIFS por padrão.

+
Quando o failover automático de LIF iSCSI é ativado, se ocorrer um failover de armazenamento, o iSCSI LIF é migrado automaticamente de seu nó ou porta inicial para seu nó ou porta parceiro de HA e, em seguida, volta assim que o failover for concluído. Ou, se a porta de um iSCSI LIF não for saudável, o LIF é migrado automaticamente para uma porta saudável em seu nó inicial atual e, em seguida, de volta para sua porta original quando a porta estiver funcionando novamente.

* FabricPool
* Provisionamento de espessura de LUN
* MetroCluster
* Protocolos de objetos
* ONTAP S3 SnapMirror e S3 APIs


.Os sistemas ASA R2 suportam o seguinte:
* SnapLock
+
link:../secure-data/ransomware-protection.html["Saiba como bloquear instantâneos"] No seu sistema ASA R2.

* Criptografia de camada dupla
+
link:../secure-data/encrypt-data-at-rest.html["Saiba como aplicar criptografia de camada dupla"] Para dados no seu sistema ASA R2.





== Suporte para replicação SnapMirror

A replicação SnapMirror é suportada em sistemas ASA r2 com as seguintes limitações:

* A replicação síncrona do SnapMirror não é suportada.
* O SnapMirror ActiveSync é compatível apenas entre dois sistemas ASA R2.
* A replicação assíncrona do SnapMirror é suportada apenas entre dois sistemas ASA r2. A replicação assíncrona do SnapMirror não é suportada entre um sistema ASA r2 e um sistema ASA, AFF ou FAS , ou a nuvem.
+
Saiba mais sobrelink:data-protection/pre-defined-protection-policies.html["Políticas de replicação SnapMirror suportadas em sistemas ASA r2"] .



.Para mais informações
* Consulte o link:https://hwu.netapp.com/["NetApp Hardware Universe"^] para obter mais informações sobre o suporte e limitações de hardware do ASA R2.

