---
sidebar: sidebar 
permalink: manage-data/create-host-groups.html 
keywords: create host group, map storage units, host access, asa r2 
summary: Crie grupos de hosts para fornecer aos hosts acesso às unidades de armazenamento e gerenciar mapeamentos de armazenamento de forma eficaz. 
---
= Crie grupos de hosts no seu sistema ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Em um sistema ASA R2, um _grupo de hosts_ é o mecanismo usado para dar aos hosts acesso a unidades de armazenamento. Um grupo de hosts se refere a um iggroup para hosts SCSI ou a um subsistema NVMe para hosts NVMe. Um host só pode ver as unidades de armazenamento mapeadas para os grupos de hosts aos quais pertence. Quando um grupo de hosts é mapeado para uma unidade de armazenamento, os hosts que são membros do grupo são então capazes de montar (criar diretórios e estruturas de arquivo) a unidade de armazenamento.

Os grupos de hosts são criados automaticamente ou manualmente quando você cria suas unidades de storage. Opcionalmente, você pode usar as etapas a seguir para criar grupos de hosts antes ou depois da criação da unidade de armazenamento.

.Passos
. No System Manager, selecione *Host*.
. Selecione os hosts que você deseja adicionar ao grupo de hosts.
+
Depois de selecionar o primeiro host, a opção para adicionar a um grupo de hosts aparece acima da lista de hosts.

. Selecione *Adicionar ao grupo anfitrião*.
. PESQUISE e selecione o grupo de hosts ao qual você deseja adicionar o host.


.O que se segue?
Você criou um grupo de hosts e agora pode link:provision-san-storage.html#map-the-storage-unit-to-a-host["mapeie-o para uma unidade de armazenamento"] .
