---
sidebar: sidebar 
permalink: manage-data/storage-limits.html 
keywords: storage limits, cluster limits, maximum lun size, maximum, nodes per cluster, storage unit size, supported protocols, asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30 
summary: Para obter o melhor desempenho, configuração e suporte, você deve estar ciente dos limites de armazenamento do ASA r2. 
---
= Determine os limites de armazenamento do seu sistema ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para obter o melhor desempenho, configuração e suporte, você deve estar ciente dos limites de armazenamento do ASA r2.

Os limites podem variar dependendo do seu sistema ASA r2 e da sua versão do ONTAP. Consulte link:https://hwu.netapp.com/["NetApp Hardware Universe"^] para obter a lista completa dos limites mais recentes para o seu sistema específico.


NOTE: Os sistemas ASA r2 estão listados no NetApp Hardware Universe em *Produtos* como plataformas "ASA".

.Passos
. Acesse link:https://hwu.netapp.com["NetApp Hardware Universe"^].
. Selecione *Produtos*.
. Em *Plataformas*, selecione *ASA* como seu tipo de sistema.
. Selecione o seu sistema específico e, em seguida, selecione a sua versão do ONTAP.
. Selecione *Mostrar resultados*.


.Resultados
Os limites suportados para o seu sistema ASA r2 específico e versão do ONTAP são exibidos.
