---
sidebar: sidebar 
permalink: monitor/monitor-storage.html 
keywords: monitor, storage, cluster, utilization, usage 
summary: Monitore a utilização do storage para garantir que você tenha a capacidade de storage necessária para atender a workloads atuais e futuros. 
searchtitle: Monitore a utilização de espaço usando o Gerenciador de sistema do ONTAP | ASA R2 
---
= Monitorar a utilização de cluster e unidades de storage em sistemas de storage ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Use o Gerenciador do sistema do ONTAP para monitorar a utilização do storage e garantir que você tenha a capacidade de storage necessária para atender a workloads atuais e futuros.



== Monitorar a utilização do cluster

Monitore regularmente a quantidade de storage consumida pelo cluster para garantir que, se necessário, esteja preparado para expandir a capacidade do cluster antes de ficar sem espaço.

.Passos
. No System Manager, selecione *Dashboard*.
. Em *Capacity*, visualize a quantidade de espaço físico usado e a quantidade de espaço disponível no cluster.
+
A taxa de redução de dados representa a quantidade de espaço economizado com a eficiência de storage.



.O que se segue?
Se o cluster estiver com pouco espaço ou se não tiver capacidade para atender a uma demanda futura, você deve Planejar link:../administer/increase-storage-capacity.html["adicionar novas unidades"]seu sistema ASA R2 para aumentar a capacidade de storage.



== Monitorar a utilização de zona de disponibilidade de storage

Cada par de HA em um sistema ASA R2 usa um pool comum de armazenamento chamado _zona de disponibilidade de armazenamento_. A zona de disponibilidade de storage tem acesso a todos os discos disponíveis no sistema de storage e é visível para ambos os nós do par de HA.

Se você tiver 4 ou mais nós no cluster, poderá visualizar a quantidade de espaço usada pela zona de disponibilidade de storage para cada par de HA. Essa métrica não está disponível para clusters de 2 nós.

.Passos
. No System Manager, selecione *Cluster*; em seguida, selecione *Overview*.
+
Um resumo da utilização da zona de disponibilidade de storage é exibido para cada par de HA no cluster.

. Se você quiser métricas mais detalhadas, selecione uma disponibilidade de armazenamento específica.
+
Em *Visão geral*, a capacidade da zona de disponibilidade de armazenamento, a quantidade de espaço usado e a taxa de redução de dados são exibidos.

+
Em *unidades de armazenamento* é apresentada uma lista de todas as unidades de armazenamento na zona de disponibilidade de armazenamento.



.O que se segue?
Se sua zona de disponibilidade de storage estiver com pouco espaço, você deverá Planejar link:../manage-data/move-storage-units.html["mova as unidades de armazenamento"]outra zona de disponibilidade de storage para equilibrar a utilização de storage no cluster.



== Monitorar a utilização da unidade de storage

Monitore a quantidade de storage consumida por uma unidade de storage para que você possa aumentar proativamente o tamanho da unidade de storage de acordo com as necessidades da sua empresa.

.Passos
. No System Manager, selecione *Storage*.
. Selecione a unidade de armazenamento que pretende monitorizar e, em seguida, selecione *Visão geral*.
. Em *armazenamento*, veja o seguinte:
+
** Tamanho da sua unidade de armazenamento
** Quantidade de espaço usado
** Relação de redução de dados
+
A taxa de redução de dados representa a quantidade de espaço economizado com a eficiência de storage

** Instantâneo utilizado
+
O snapshot usado representa a quantidade de storage usada pelos snapshots.





.O que se segue?
Se a sua unidade de armazenamento estiver próxima da capacidade, você deve link:../manage-data/modify-storage-units.html["modifique a unidade de armazenamento"]aumentar seu tamanho.
