---
sidebar: sidebar 
permalink: administer/rebalance-workloads.html 
keywords: rebalance workload, workload rebalancing, node balancing, asa r2 
summary: A partir do ONTAP 9.17.1, o ONTAP reequilibra automaticamente as cargas de trabalho entre os nós em um par de HA do sistema ASA r2 para desempenho ideal. 
---
= Rebalancear cargas de trabalho entre nós em sistemas de armazenamento ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.17.1, o ONTAP rebalanceia automaticamente as cargas de trabalho entre os nós em um par de HA do sistema ASA r2 para otimizar o desempenho. Por exemplo, se a utilização em um nó aumentar para 70% enquanto a utilização em seu parceiro de HA for de apenas 30%, o ONTAP desloca automaticamente as cargas de trabalho para que a utilização de cada nó seja mais equilibrada. Como os nós do par de HA compartilham a mesma zona de disponibilidade de armazenamento, o rebalanceamento da carga de trabalho é uma operação sem cópias e sem impacto no desempenho.



== Modificar o período de avaliação padrão para rebalanceamento automático de carga de trabalho

O rebalanceamento automático da carga de trabalho é habilitado por padrão 14 dias após a atualização para o ONTAP 9.17.1 ou a inicialização de um novo cluster ONTAP 9.17.1 ASA r2. Você pode usar a interface de linha de comando (CLI) do ONTAP para aumentar ou diminuir o período de avaliação padrão, de acordo com suas necessidades operacionais.

.Passos
. Verifique o número de dias restantes no período de avaliação:
+
[source, cli]
----
placement rebalance config show -fields evaluation-window
----
. Alterar o período de avaliação de rebalanceamento:
+
[source, cli]
----
placement rebalance config modify -evaluation-window <number_of_evaluation_days>
----
+
O exemplo a seguir define o período de avaliação restante para 10 dias.

+
[listing]
----
placement rebalance config modify -evaluation-window 10
----




== Modificar a configuração de rebalanceamento automático da carga de trabalho

O rebalanceamento automático da carga de trabalho é habilitado por padrão 14 dias após a atualização para o ONTAP 9.17.1 ou a inicialização de um novo cluster ONTAP 9.17.1 ASA r2. Você pode alterar a configuração padrão para desabilitar o rebalanceamento automático da carga de trabalho ou defini-lo como um estado de alerta para sinalizar cargas de trabalho desbalanceadas sem movê-las automaticamente.

.Passo
. Verifique o modo de rebalanceamento atualmente definido em seus nós:
+
[source, cli]
----
placement rebalance config show -fields mode
----
. Modifique a configuração de rebalanceamento automático da carga de trabalho:
+
[source, cli]
----
placement rebalance config modify -mode <disabled|advisory|automated>
----
. Verifique se o modo de rebalanceamento foi modificado:
+
[source, cli]
----
placement rebalance config show -fields mode
----




== Acionar manualmente o rebalanceamento da carga de trabalho

Se você desativou o rebalanceamento automático da carga de trabalho, ainda poderá acioná-lo manualmente. Isso é útil se você quiser rebalancear cargas de trabalho após um período de ajustes manuais ou se tiver definido o modo de rebalanceamento como *consultivo* e quiser tomar medidas com base nos sinalizadores da carga de trabalho.

.Passos
. Verifique o modo de rebalanceamento atualmente definido em seus nós:
+
[source, cli]
----
placement rebalance config show -fields mode
----
. Se o modo de rebalanceamento não estiver definido como *consultivo*, defina-o como *consultivo*:
+
[source, cli]
----
placement rebalance config modify -mode advisory
----
. Acionar manualmente um rebalanceamento de carga de trabalho:
+
[source, cli]
----
balanced-placement rebalance execute
----
. Veja o status da operação de rebalanceamento:
+
[source, cli]
----
placement rebalance config show-evaluation
----


.O que se segue?
Se você quiser definir o modo de rebalanceamento como *automatizado* ou *desativado*, você pode fazer isso usando o  `placement rebalance config modify` comando.
