---
sidebar: sidebar 
permalink: administer/upgrade-ontap.html 
keywords: update, firmware, system files, automatic updates, automated updates, asa r2, disable, 
summary: As atualizações de software ONTAP para sistemas ASA r2 seguem o mesmo processo de atualizações para outros sistemas ONTAP .  Ao atualizar seu software ONTAP no seu sistema ASA r2, você pode aproveitar os novos e aprimorados recursos do ONTAP . 
---
= Atualizar o ONTAP em sistemas de storage ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao atualizar o software ONTAP no sistema ASA R2, você pode aproveitar os novos e aprimorados recursos do ONTAP que ajudam a reduzir custos, acelerar workloads críticos, melhorar a segurança e expandir o escopo de proteção de dados disponível para sua organização.

As atualizações de software ONTAP para sistemas ASA r2 seguem o mesmo processo que as atualizações para outros sistemas ONTAP. Recomenda-se que você comece por link:https://docs.netapp.com/us-en/ontap/upgrade/create-upgrade-plan.html["Preparando-se para a sua atualização com Upgrade Advisor no Active IQ Digital Advisor ou Upgrade Health Checker"].

Depois de se preparar para a atualização, é recomendável que você execute atualizações usando link:https://docs.netapp.com/us-en/ontap/upgrade/task_upgrade_andu_sm.html["Atualização automatizada e sem interrupções (ANDU) do System Manager"]o . O ANDU aproveita a tecnologia de failover de alta disponibilidade (HA) da ONTAP para garantir que os clusters continuem fornecendo dados sem interrupção durante a atualização.

Saiba mais link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["Atualizações de software ONTAP"]sobre o .
