---
sidebar: sidebar 
permalink: get-started/learn-about.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, learn more, learn about, get started 
summary: 'Os sistemas ASA r2 (ASA A1K, A90, A70, A50, A30, A20, C30) oferecem uma solução unificada de hardware e software para uma experiência simplificada para clientes somente SAN.' 
searchtitle: Saiba mais sobre os sistemas ASA A1K, A90, A70, A50, A30 A20 e C30 
---
= Saiba mais sobre os sistemas de armazenamento ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os sistemas NetApp ASA r2 oferecem uma solução unificada de hardware e software que simplifica a experiência para clientes que utilizam apenas SAN. Em um sistema ASA r2, o software ONTAP e o System Manager são otimizados para oferecer suporte às funcionalidades essenciais de SAN, removendo recursos desnecessários em ambientes SAN.

Os seguintes sistemas são classificados como sistemas ASA r2:

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20
* ASA C30


.Unidades de armazenamento e grupos de consistência
Os sistemas ASA R2 introduzem o uso de unidades de storage com grupos de consistência:

* Uma _unidade de armazenamento_ torna o espaço de armazenamento disponível para seus hosts SAN para operações de dados. Uma unidade de storage refere-se a um LUN para hosts SCSI ou a um namespace NVMe para hosts NVMe.
* _Um grupo de consistência_ é uma coleção de unidades de armazenamento que são gerenciadas como uma única unidade.


Os sistemas ASA r2 utilizam unidades de armazenamento com grupos de consistência para simplificar o gerenciamento de storage e a proteção de dados. Por exemplo, suponha que você tenha um banco de dados composto por 10 unidades de armazenamento em um grupo de consistência e precise fazer backup de todo o banco de dados. Em vez de fazer backup de cada unidade de armazenamento individualmente, você pode proteger todo o banco de dados fazendo backup do grupo de consistência.

.Proteção e segurança de dados
Para ajudar a proteger seus dados contra ataques maliciosos, como roubo ou ransomware, os sistemas ASA r2 oferecem suporte a um gerenciador de chaves integrado, criptografia em duas camadas, autenticação multifator e verificação multiadministrador. Você também pode replicar snapshots para um local secundário e usar o SnapLock for SnapVault para proteger os snapshots de destino contra exclusão acidental ou maliciosa.

.Protocolos suportados, multipathing e configurações
Os sistemas ASA r2 suportam todos os protocolos SAN (iSCSI, FC, NVMe/FC, NVMe/TCP). Todos os protocolos suportam arquitetura ativo-ativo simétrica para multipathing, garantindo que todos os caminhos entre os hosts e o armazenamento estejam ativos/otimizados. Os protocolos iSCSI e NVMe/TCP suportam configurações de rede e de conexão direta para todas as versões do ONTAP suportadas. Os protocolos FC e NVMe/FC suportam configurações de rede para todas as versões do ONTAP suportadas e, a partir do ONTAP 9.19.1, também suportam configuração de conexão direta. Os sistemas ASA r2 não suportam a combinação de clusters com sistemas ASA, AFF ou FAS.

* Saiba mais sobre link:https://docs.netapp.com/us-en/ontap/san-admin/multipath-automatic-lif-failover-support.html["Suporte a multipath SAN"^].
* Saiba mais sobre link:https://docs.netapp.com/us-en/ontap/san-config/configure-iscsi-san-hosts-ha-pairs-reference.html["Configurações para os protocolos iSCSI e NVMe/TCP"^].
* Saiba mais sobre link:https://docs.netapp.com/us-en/ontap/san-config/configure-fc-nvme-hosts-ha-pairs-reference.html["Configurações para os protocolos FC e NVMe/FC"^].


.Informações relacionadas
* Saiba mais sobre o suporte e as limitações dos sistemas ASA R2 no link:https://hwu.netapp.com/["NetApp Hardware Universe"^].
* Saiba mais link:../learn-more/hardware-comparison.html["Os sistemas ASA R2 em comparação com os sistemas ASA"]sobre o .
* Saiba mais sobre o link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"^].

