---
sidebar: sidebar 
permalink: data-protection/manage-consistency-groups.html 
keywords: consistency groups, snapshots, data protection, protect data, add, remove, delete, storage units, lun, namespace, increase capacity 
summary: Use grupos de consistência para executar várias ações em várias unidades de armazenamento ao mesmo tempo em vez de executar ações individualmente em cada unidade. 
---
= Saiba mais sobre grupos de consistência ONTAP em sistemas de armazenamento ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um grupo de consistência é uma coleção de unidades de armazenamento que são gerenciadas como uma única unidade.  Use grupos de consistência para simplificar o gerenciamento de armazenamento.

Por exemplo, suponha que você tenha um banco de dados com 10 unidades de armazenamento em um grupo de consistência e precise fazer backup de todo o banco de dados. Em vez de fazer backup de cada unidade de armazenamento, você pode fazer backup de todo o banco de dados simplesmente adicionando proteção de dados de instantâneo ao grupo de consistência.  Fazer backup das unidades de armazenamento como um grupo de consistência em vez de individualmente também fornece um backup consistente de todas as unidades, enquanto fazer backup das unidades individualmente pode criar inconsistências.

A partir do ONTAP 9.16.1, você pode usar o System Manager para criar grupos de consistência hierárquicos no seu sistema ASA r2.  Em uma estrutura hierárquica, um ou mais grupos de consistência são configurados como filhos em um grupo de consistência pai.

Os grupos hierárquicos de consistência permitem que você aplique políticas de snapshot individuais a cada grupo filho de consistência e replique os snapshots de todos os grupos filhos de consistência a um cluster remoto como uma única unidade replicando o pai. Isso simplifica a proteção e o gerenciamento de dados para estruturas de dados complexas. Por exemplo, suponha que você crie um grupo de consistência pai chamado `SVM1_app` que contém dois grupos de consistência filhos: `SVM1app_data` Para dados de aplicativos e `SVM1app_logs` para logs de aplicativos. Os instantâneos de `SVM1app_data` são tirados a cada 15 minutos e os instantâneos de são tirados a `SVM1app_logs` cada hora. O grupo de consistência pai `SVM1_app,` tem uma política do SnapMirror que replica os snapshots de ambos `SVM1app_data` e `SVM1app_logs` para um cluster remoto a cada 24 horas. O grupo de consistência pai `SVM1_app` é gerenciado como uma única unidade e os grupos de consistência filho são gerenciados como unidades separadas.



== Grupos de consistência em relacionamentos de replicação

A partir do ONTAP 9.17.1, você pode fazer as seguintes alterações de geometria em grupos de consistência em um relacionamento de replicação assíncrona ou em um relacionamento de sincronização ativa do SnapMirror sem interromper ou excluir o relacionamento.  Quando ocorre uma alteração de geometria no grupo de consistência primário, a alteração é replicada para o grupo de consistência secundário.

* link:manage-consistency-groups-add-remove-storage-units.html["Modificar o tamanho de uma unidade de armazenamento"]adicionando ou removendo unidades de armazenamento.
* link:manage-hierarchical-consistency-groups.html#promote-an-existing-consistency-group-into-a-parent-consistency-group["Promova um único grupo de consistência"]para um grupo de consistência pai.
* link:manage-hierarchical-consistency-groups.html#demote-a-parent-consistency-group-to-a-single-consistency-group["Rebaixar um grupo de consistência pai"]para um único grupo de consistência.
* link:manage-hierarchical-consistency-groups.html#detach-a-child-consistency-group-from-a-parent-consistency-group["Desanexar um grupo de consistência filho"]de um grupo de consistência pai.
* link:manage-hierarchical-consistency-groups.html#create-a-child-consistency-group["Crie um grupo de consistência filho"]usando um grupo de consistência existente.


No ONTAP 9.16.1, você develink:snapmirror-active-sync-break-relationship.html["quebrar o relacionamento de replicação assíncrona"] elink:snapmirror-active-sync-delete-relationship.html["excluir o relacionamento de sincronização ativa do SnapMirror"] antes de fazer alterações de geometria no grupo de consistência.
