---
sidebar: sidebar 
permalink: release-notes/changes-to-limits-defaults.html 
keywords: release notes, changes, updates, defaults, limits, asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30 
summary: Saiba mais sobre as alterações nos limites e padrões que afetam os sistemas ASA R2. 
---
= Alterações nos limites e padrões do ONTAP que afetam os sistemas ASA R2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Saiba mais sobre as alterações nos limites e padrões que afetam os sistemas ASA R2. A NetApp se esforça para ajudar seus clientes a entender os padrões mais importantes e limitar as alterações em cada versão do ONTAP.



== Alterações nos limites do ONTAP

[cols="2,4,4"]
|===
| Recurso | Limite de alteração | Alterado na versão... 


| VMs de armazenamento por cluster | O número máximo de máquinas virtuais (VMs) de armazenamento suportadas por par HA foi aumentado de 32 para 256. | ONTAP 9.18.1 


| SnapMirror sincronização ativa | O suporte para sincronização ativa do SnapMirror foi ampliado de clusters de dois nós para clusters de quatro nós. | ONTAP 9.18.1 


| Nós por cluster  a| 
O número máximo de nós por cluster aumenta de 2 para 12.


NOTE: Se você estiver executando o ONTAP 9.16.1 com mais de 2 nós em um cluster, não será possível reverter para o ONTAP 9.16.0.
| ONTAP 9.16,1 


| Unidades de armazenamento | O número máximo de unidades de storage é aumentado de 2500 por par de HA para 10.000 por par de HA. | ONTAP 9.16,1 
|===