---
sidebar: sidebar 
permalink: release-notes/whats-new-9160.html 
keywords: 'what"s new, release notes, 9.16.0, asa r2, asa a1k, asa a90, asa a70' 
summary: Saiba mais sobre os novos recursos disponíveis no ONTAP 9.16,0 para sistemas ASA R2. 
---
= Novidades do ONTAP 9.16,0 para sistemas ASA R2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Saiba mais sobre os novos recursos disponíveis no ONTAP 9.16,0 para sistemas ASA R2.



== Sistemas

[cols="2,4"]
|===
| Atualização | Descrição 


| Sistemas  a| 
Os seguintes sistemas NetApp ASA r2 estão disponíveis.  Esses sistemas oferecem uma solução unificada de hardware e software que cria uma experiência simplificada, específica para as necessidades de clientes que utilizam apenas SAN.

* ASA A1K
* ASA A70
* ASA A90


|===


== System Manager

[cols="2,4"]
|===
| Atualização | Descrição 


| link:../get-started/learn-about.html["Suporte otimizado para clientes somente de SAN"] | O System Manager é otimizado para oferecer suporte à funcionalidade essencial de SAN, ao mesmo tempo em que remove a visibilidade de recursos e funções não compatíveis em ambientes SAN. 
|===


== Gerenciamento de storage

[cols="2,4"]
|===
| Atualização | Descrição 


| link:../manage-data/provision-san-storage.html["Gerenciamento simplificado de storage"]  a| 
Os sistemas ASA R2 apresentam o uso de unidades de storage com grupos de consistência para gerenciamento simplificado de storage.

* Uma _unidade de armazenamento_ torna o espaço de armazenamento disponível para seus hosts SAN para operações de dados. Uma unidade de storage refere-se a um LUN para hosts SCSI ou a um namespace NVMe para hosts NVMe.
* _Um grupo de consistência_ é uma coleção de unidades de armazenamento que são gerenciadas como uma única unidade.


|===


== Segurança dos dados

[cols="2,4"]
|===
| Atualização | Descrição 


| link:../secure-data/encrypt-data-at-rest.html["Gerenciador de chaves integrado e criptografia de camada dupla"]  a| 
Os sistemas ASA R2 são compatíveis com um gerenciador de chaves integrado e criptografia de camada dupla (hardware e software).

|===